version: "3.8"

services:
  app:
    build:
      context: ./app
    ports:
      - "8000:8000"
    env_file:
      - .env
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
